export const EN = `Mr. Park founded HKD in 1980 and currently serves as its Chairman. The company has offices in the United States, Korea, Hong Kong, and Bangladesh. HKD Global is one of the world's leading manufacturers of high-quality tents, shelters, and camping equipment. HKD Outdoor Innovations Ltd. specializes in the manufacturing of outdoor and sportswear apparel. The company currently manufactures a wide range of products, including rainwear, padded jackets, down jackets, hunting wear, casual wear, and knitwear.`;

export const XEN = [
  'outdoor',
  'innovations',
  'manufacturing',
  'garment',
  'jacket',
  'fleece',
  'sportswear',
  'buyer',
  'order',
  'quantity',
  'production',
  'quality',
  'factory',
  'shipment',
  'Decathlon',
  'Columbia',
  'Walmart',
  'Bangladesh',
  'company',
  'chairman',
  'knitwear',
  'department',
  'employee',
  'management',
  'technology',
  'HKD',
  'Mr. Park',
  'HKD Global',
  'HKD Outdoor Innovations Ltd.',
  'United States',
  'Korea',
  'Hong Kong',
  'tents',
  'shelters',
  'camping equipment',
  'rainwear',
  'padded jackets',
  'down jackets',
  'hunting wear',
  'casual wear',
  'sportswear apparel'
];
